### ISSUE TITLE
Replace `Output` objects with a generic `FILE*`

### ISSUE THREAD

**Issue by ghost** [enioluwa23/ackermann-visualizer#3]
It seems a bit strange to have an entire object hierarchy when C/C++'s `FILE*` structure handles file output generically already for both regular files and tty output. Since `Output::writef` is essentially `printf` and and `Output::writeln` is essentially `puts`, why not just switch to using `fprintf` and `fputs` for both console output and file output?

**Comment by enioluwas** [comment]
Good point. The I/O bridge was the Enterprise Edition Developer in me lashing out.

**Comment by ghost** [comment]
@enioluwa23 The lack of an `AbstractOutputFactory`  was making it very difficult to take this project seriously as an enterprise solution.
